### ISSUE TITLE
Remove "rosalind_uge" from repository

### ISSUE THREAD

**Issue by Ethan-Hetrick** [nf-core/configs#693]
Hello there! I am a bioinformatics scientist contractor working out of CDC (U.S.) for a group named SciComp. We manage the scientific computing infrastructure at CDC, including the Rosalind HPC cluster. One of our users, Gregory Sprenger, submitted the "rosalind_uge" config to nf-core a while back. Our group never approved of this, so we request that it be taken off of the repository. We have decided for the time being to maintain our own configuration files that users are instructed to use, so we do not want any configuration specific to CDC compute environments in nf-core. 

Config in question: conf/rosalind_uge.config

Thank you for taking time to consider this issue, we appreciate it greatly.

**Comment by jfy133** [comment]
Hi @Ethan-Hetrick 

Sorry to hear you're not happy with this.

I won't be able to get to this until next week, however you're happy to open a PR if you wish (you can check the readme and reverse engineer what gets added, should be about 5 files).

But please note I just checked the config and I see there Is basically no special or cluster specific stuff there other than the queue names which are very generic.

You may have other reasons for removing this, but just wanted to let you know that it shouldn't be doing any 'harm' of youre concerned with security risks or something similar.

**Comment by jfy133** [comment]
Just thinking a little more (sorry, it's end of day here and been juggling kids), I think rather than remove it straight away, I would suggest we add a deprecation notice first, leave it for 2 weeks just in case there are some users still using it, then we remove it. 

I think this would be a bit nicer on users, particularly as I (personally) can't see any major issues with the config itself.

 Would that be alright, if you really don't want the config to be on here?

**Comment by jfy133** [comment]
As other users use the cluster, I think it's her a bad idea to remove it.

@gregorysprenger has removed references to your group as a support for that particular config, so you don't have to be responsible for it.

If it helps we could add a message in the description saying 'unofficial' or ' unsupported by <your group>' to discourage users on your own institution from using it.

**Comment by slsevilla** [comment]
I'm Sam, Ethan's manager. I'll intercede here since I assigned this to him.

It may be true that this config was/is used outside of the CDC, however, it when Ethan made the request, it referenced our CDC specific group, which did not support or approve this configuration file. Our team is responsible for this cluster, and so the request was made to ensure that was not confusion as to our approval for its usage.
```
If assistance is needed, please contact the Scientific Computing and Bioinformatics department (SciComp).
```

I see now that our group's name has been removed in which case there is no longer an issue. I don't think an unsupported/unofficial tag is necessary, at this time.

Thanks all!
